{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.names.configmap }}
  namespace: {{ .Values.namespace }}
data:
{{- range $k, $v := .Values.configmap.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}