{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.names.secret }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secret.stringData }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}