apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
  namespace: ecuaalejo2013-dev
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.names.app }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}