name: CI-HelmBuild

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry-1.docker.io
      NAMESPACE: ${{ secrets.DOCKER_USERNAME }}     # tu usuario de Docker Hub
      CHART_NAME: mi-chart
      CHART_VERSION: 0.1.${{ github.run_number }}   # SemVer válido
      APP_VERSION: ${{ github.sha }}                # opcional

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      # (Opcional) login con Docker; no molesta
      - name: Log in to Docker Hub (docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login específico de Helm para OCI
      - name: Log in to Docker Hub (helm/OCI)
        run: |
          helm registry login $REGISTRY \
            --username "${{ secrets.DOCKER_USERNAME }}" \
            --password "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Package chart (set version/appVersion)
        run: |
          helm package ./mi-chart \
            --version "${CHART_VERSION}" \
            --app-version "${APP_VERSION::7}"
          ls -l

      - name: Push chart to Docker Hub (OCI)
        run: |
          helm push "${CHART_NAME}-${CHART_VERSION}.tgz" oci://$REGISTRY/${NAMESPACE}
